### ISSUE TITLE
Furniture Preview

### ISSUE THREAD

**Issue by Lyhtande** [Rhyono/CraftStore#16]
I would like to ask if  [Furniture Preview modified by Teva](https://www.esoui.com/downloads/info2970-FurniturePreviewmodifiedbyTeva.html) could be used for the Item Preview in the furniture window in case this is possible at all. Otherwise  the mouse button hint in the tooltips ([screenshot](https://i.imgur.com/19u7Xs3.png)) could be removed, since the original [ItemPreview](https://www.esoui.com/downloads/info1622-ItemPreviewdiscontinued.html) by Shinni is discontinued.

**Comment by MuMuQ** [comment]
@Lyhtande I had a look at the addon you linked. It seems that ZOS indeed restricted the ability to preview furniture items to items that are in some sort of inventory (i.e. inventory, bank or guild bank). The preview based on `itemId`s / `itemLink`s is prohibited by ZOS and will result in an error message. :(

I'll probably remove the mouse button hint then :/

**Comment by Lyhtande** [comment]
Hello @MuMuQ ,
thanks for looking into the Furniture Preview addon! Too sad it's impossible..

**Comment by Rhyono** [comment]
This won't be coming back due to ZOS, so I'm closing this issue.
