### ISSUE TITLE
 Mass Fillet to Craftstore Cook

### ISSUE THREAD

**Issue by tbagwell** [Rhyono/CraftStore#32]
Can you add mass fillet fish. This feature was added with necrom when using a provisioning station. And would be nice to do it within craftstore cook without having to disable it.

**Comment by Rhyono** [comment]
MuMuQ is looking into whether it's possible.

**Comment by MuMuQ** [comment]
I think I managed to create a semi-good solution... a button that hides CraftStoreCook and jumps to the vanilla filleting UI.

The functions for filleting fish are currently locked down so this will have to do for now.

@tbagwell You can try the feature by downloading the addon from the feature branch and installing it manually: https://github.com/MuMuQ/CraftStore/archive/refs/heads/feature/fish-fillet.zip

**Comment by tbagwell** [comment]
In testing it.. You can push the button to change back over to Vanilla.. You can click on the fish but you don't have a button or command to do on and fillet them.. Or I don't see it on my screen

**Comment by tbagwell** [comment]
Here is a pic of my screen
![craftstore fish](https://github.com/Rhyono/CraftStore/assets/35106570/0c926577-c580-4024-bd50-8b8101a97bff)

**Comment by MuMuQ** [comment]
Curious as I thought I fixed that in a second commit. Not sure if the link above leads to a version that includes that commit (even though it should).

![Screenshot_20230823_001627](https://github.com/Rhyono/CraftStore/assets/10376200/d82c2c7e-55b3-4a43-aa4f-ad4ea35e626f)
This is how it looks for me now.

Could you please try this version, please:
https://github.com/MuMuQ/CraftStore/archive/refs/heads/release/2.87.zip

It includes all changes intended for the next CraftStore release and it's identical to what I am running on my end right now.

**Comment by tbagwell** [comment]
I tested that new file you posted. That work show up with the buttons at the bottom.. And I can use them.

Thanks you.

**Comment by MuMuQ** [comment]
Thank you for validating :) Let's see when @Rhyono manages to push out the release :)
