### ISSUE TITLE
[Request] Add explainers for CraftStoreX submodules

### ISSUE THREAD

**Issue by dethmourne** [Rhyono/CraftStore#34]
I'm looking at the CraftStore settings ingame right now and it has "Use CraftStoreQuest" but I have no idea what this is - it'd be nice to get clarity in-game.

**Comment by MuMuQ** [comment]
I added those in #39. I only added the english and german translation for now as I didn't have time to put the texts through google translate. If you're able to add any more languages (fr, br/pt, ru, it, es) you can post the texts here and I'll add them :)
