### ISSUE TITLE
UI error when hovering over the cook button

### ISSUE THREAD

**Issue by DominiqueComte** [Rhyono/CraftStore#45]
The error info:
C9743647

user:/AddOns/CraftStoreFixedAndImproved/CraftStore.lua:4175: attempt to index a nil value
stack traceback:
user:/AddOns/CraftStoreFixedAndImproved/CraftStore.lua:4175: in function 'CS.Tooltip'
	<Locals> c = ud, visible = T, scale = T, parent = ud, pos = "bc", IconScale = user:/AddOns/CraftStoreFixedAndImproved/CraftStore.lua:4089, TooltipCraft = user:/AddOns/CraftStoreFixedAndImproved/CraftStore.lua:4097, anchor = [table:1]{}, first = " " </Locals>
CraftStoreFixed_CookSpaceButton_MouseEnter:2: in function '(main chunk)'
	<Locals> self = ud </Locals>

I'll try to fix it but I'm not sure yet how to fix that.

**Comment by FHoulbreque** [comment]
It is related to a missing translation in the CraftStore_Lang.lua in any other language than German or English. They added the mention to "Fillet" option in English and forgot to add it to the long TT Object that is there.

I would suggest editing this file and adding "Fillet" in your language like I did myself in French.

```		'Filet',	```

I would like contributor that can push into this repository to make this change as well.

**Comment by Rhyono** [comment]
This should be corrected now. Let me know if not.
